# Generated by Django 5.1.7 on 2025-04-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_creator_media_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='title',
            new_name='name',
        ),
    ]
