# Generated by Django 5.1.6 on 2025-04-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_title_media_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='media',
            old_name='type',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='name',
            new_name='title',
        ),
    ]
