# Generated by Django 5.1.6 on 2025-04-05 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_media_genre_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='tab',
            field=models.CharField(blank=True, choices=[('reviews', 'Reviews'), ('characters', 'Characters'), ('plot', 'Plot'), ('visuals', 'Visuals')], max_length=20, null=True),
        ),
    ]
