# Generated by Django 5.1.6 on 2025-04-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_message_media_message_room_room_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tab',
            field=models.CharField(choices=[('reviews', 'Reviews'), ('characters', 'Characters'), ('plot', 'Plot'), ('visuals', 'Visuals')], default='Reviews', max_length=20),
            preserve_default=False,
        ),
    ]
