# Generated by Django 5.1.6 on 2025-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='media',
            name='genre',
        ),
        migrations.AddField(
            model_name='media',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='created_media', to='base.creator'),
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='media_items', to='base.genre'),
        ),
    ]
