# Generated by Django 5.1.7 on 2025-04-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_media_creator_remove_media_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='creators',
        ),
        migrations.AddField(
            model_name='media',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.creator'),
        ),
    ]
