# Generated by Django 5.1.7 on 2025-04-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_media_creators_media_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='poster',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
