# Generated by Django 5.1.7 on 2025-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_media_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
