# Generated by Django 5.1.7 on 2025-04-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_media_creator_media_creators'),
        ('base', '0013_alter_media_poster'),
    ]

    operations = [
    ]
