# Generated by Django 5.2 on 2025-04-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_media_creator_media_creators'),
        ('base', '0013_alter_media_poster'),
    ]

    operations = [
    ]
