# Generated by Django 5.1.7 on 2025-04-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_media_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='creators',
        ),
        migrations.AddField(
            model_name='media',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_media', to='base.creator'),
        ),
        migrations.RemoveField(
            model_name='media',
            name='genres',
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='base.genre'),
        ),
    ]
