# Generated by Django 5.1.7 on 2025-04-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_merge_20250409_2215'),
        ('base', '0017_remove_media_creators_media_creator_and_more'),
    ]

    operations = [
    ]
