# Generated by Django 5.1.7 on 2025-04-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_merge_20250408_1721'),
        ('base', '0018_merge_20250410_1049'),
    ]

    operations = [
    ]
