# Generated by Django 5.1.7 on 2025-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_merge_20250410_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='creator',
        ),
        migrations.AddField(
            model_name='media',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='created_media', to='base.creator'),
        ),
    ]
