# Generated by Django 5.1.5 on 2025-04-24 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_media_creator_media_creators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='media',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorite_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
