# Generated by Django 5.1.5 on 2025-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_media_options_media_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='genres',
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='media_items', to='base.genre'),
        ),
    ]
