# Generated by Django 5.1.7 on 2025-04-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0004_rename_title_media_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='media_types',
        ),
        migrations.AddField(
            model_name='profile',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.type'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_titles',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_titles',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='base.media'),
        ),
    ]
