# Generated by Django 5.1.6 on 2025-04-03 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_media_types_profile_type_and_more'),
        ('base', '0005_genre_rename_type_media_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Type',
            new_name='media_types',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, to='base.genre'),
        ),
    ]
