# Generated by Django 5.1.6 on 2025-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_type_profile_media_types_profile_friends_and_more'),
        ('base', '0005_genre_rename_type_media_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='media_types',
        ),
        migrations.AddField(
            model_name='profile',
            name='media_types',
            field=models.ManyToManyField(blank=True, to='base.type'),
        ),
    ]
