# Generated by Django 5.1.5 on 2025-04-25 15:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_media_types_profile_media_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/images/avatar.svg', upload_to=accounts.models.user_directory_path),
        ),
    ]
