# Generated by Django 5.1.5 on 2025-04-25 20:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../images/avatar.svg', upload_to=accounts.models.user_directory_path),
        ),
    ]
